version: "3"
services:
  openq-json-rpc-node:
    image: alo42/openq-json-rpc-node:latest
    ports:
      - "8545:8545"
  openq-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./OpenQ-API
    ports:
      - "8090:8090"
    env_file:
      - ./OpenQ-API/.env.docker
    volumes:
      - /app/node_modules
      - ./OpenQ-API:/app
  openq-frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./OpenQ-Frontend
    ports:
      - "3000:3000"
    env_file:
      - ./OpenQ-Frontend/.env.${DEPLOY_ENV}
    volumes:
      - /app/node_modules
      - ./OpenQ-Frontend:/app
    entrypoint: ["yarn", "boot:${DEPLOY_ENV}"]
  github-oauth-server:
    build:
      dockerfile: Dockerfile
      context: ./OpenQ-Github-OAuth-Server
    ports:
      - "3001:3001"
    env_file:
      - ./OpenQ-Github-OAuth-Server/.env
    volumes:
      - /app/node_modules
      - ./OpenQ-Github-OAuth-Server:/app