version: "3"
services:
  openq-api:
    container_name: openq-api
    build:
      dockerfile: Dockerfile.dev
      context: ./OpenQ-API
    env_file:
      - ./OpenQ-API/.env
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./OpenQ-API:/app
  mongo:
    container_name: mongo
    image: openq/mongo-local-replica-set:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
      - openq-api
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27018
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    ports:
      - "8888:8081"
    restart: unless-stopped
