version: "3"
services:
  openq-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./OpenQ-API
    ports:
      - "8090:8090"
    env_file:
      - ./OpenQ-API/.env.docker
    volumes:
      - /app/node_modules
      - ./OpenQ-API:/app
  openq-frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./OpenQ-Frontend
    ports:
      - "3000:3000"
    env_file:
      - ./OpenQ-Frontend/.env
    volumes:
      - /app/node_modules
      - ./OpenQ-Frontend:/app
    entrypoint: ["yarn", "boot:${DEPLOY_ENV}"]